bigquery:
  target: prod
  outputs:
    prod:
      type: bigquery
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      project: "{{ env_var('DBT_GOOGLE_PROJECT') }}"
      dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET') }}"
      threads: 2
