name: DBT

on:
  push:
    branches: [main]
    paths:
      - "dbt/**"
  schedule:
    - cron: "0,30 * * * *"

env:
  DBT_PROFILES_DIR: ./dbt
  DBT_POSTGRES_HOSTNAME: ${{secrets.DBT_POSTGRES_HOSTNAME}}
  DBT_POSTGRES_USER: ${{secrets.DBT_POSTGRES_USER}}
  DBT_POSTGRES_PASSWORD: ${{secrets.DBT_POSTGRES_PASSWORD}}
  DBT_POSTGRES_PORT: ${{secrets.DBT_POSTGRES_PORT}}
  DBT_POSTGRES_DBNAME: ${{secrets.DBT_POSTGRES_DBNAME}}

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - run: pip3 install dbt
      - run: dbt --version
      # - run: 'echo "$KEYFILE" > ./profiles.yml'
      #   shell: bash
      #   env:
      #     KEYFILE: profiles_tmp.yml
      # - run: cat ./profiles.yml
      - run: dbt run --profiles-dir .
      - run: dbt test
