name: DBT

on:
  push:
    branches: [main]
    paths:
      - "dbt/**"
  schedule:
    - cron: "0,30 * * * *"

env:
  DBT_PROFILES_DIR: ./dbt
  DBT_GOOGLE_PROJECT: reflection-323614
  DBT_GOOGLE_BIGQUERY_DATASET: default
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./.gcloud/dbt-service-account.json

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - run: pip3 install dbt-core dbt-bigquery
      - run: dbt --version
      - run: mkdir ./.gcloud/
      - run: 'echo "$KEYFILE" > ./.gcloud/dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
      - run: dbt run --profiles-dir .
      # - run: dbt test
